name: "Test this PR"
author: "Sarah Gibson"
description: |
  Copy a PR from a forked repo into a branch on the parent repo so that
  workflows that require secrets can be run
inputs:
  repository:
    description: "The repository id in the form 'owner/project'"
    required: false
    default: ${{ github.repository }}
  github-issue-context:
    description: "The workflow context from the issue that triggered the run"
    required: false
    default: ${{ github.event.issue }}
  github-token:
    description: |
      A GitHub token with enough permissions to write to the parent repo
    required: false
    default: ${{ github.token }}
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.github-issue-context }}
    - ${{ inputs.github-token }}
