name: "Test this PR"
author: "Sarah Gibson"
description: |
  Copy a PR from a forked repo into a branch on the parent repo so that
  workflows that require secrets can be run
inputs:
  repository:
    description: "The repository id in the form 'owner/project'"
    required: false
    default: ${{ github.repository }}
  github-context:
    description: "The workflow context from the issue that triggered the run"
    required: false
    default: ${{ toJson(github.event) }}
  github-token:
    description: |
      A GitHub token with enough permissions to write to the parent repo
    required: false
    default: ${{ github.token }}
  author-name:
    description: |
      The name of the user that will be displayed as the author of the commit
    required: false
    default: "CI User"
  author-email:
    description: |
      The email of the user that will be displayed as the author of the commit
    required: false
    default: "ci-user@github.local"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.repository }}
    - ${{ inputs.github-context }}
    - ${{ inputs.github-token }}
    - ${{ inputs.author-name }}
    - ${{ inputs.author-email }}
